apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  type: NodePort
